### ISSUE TITLE
Volume Expansion

### ISSUE THREAD

**Issue by jleavers** [vmware/cloud-director-named-disk-csi-driver#27]
### Describe the bug

I have created a storage class:

```
apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: pure
provisioner: named-disk.csi.cloud-director.vmware.com
reclaimPolicy: Delete
parameters:
  storageProfile: "Pure"
  filesystem: "ext4"
allowVolumeExpansion: true
```

I can create a PVC: 

```
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
test   Bound    pvc-acd8f9a9-dcd3-4735-9888-7d2d9748c659   1Gi        RWO            pure           12m
```

However if I edit the PVC and change spec.resources.requests.storage to a new size, e.g. 2Gi, the change doesn't happen and the following is logged:

```
Events:
  Type     Reason                 Age                   From                                                                                                      Message
  ----     ------                 ----                  ----                                                                                                      -------
  Normal   Provisioning           8m5s                  named-disk.csi.cloud-director.vmware.com_csi-vcd-controllerplugin-0_097b7dca-fddc-4972-bcc2-b0b6e9d30b62  External provisioner is provisioning volume for claim "default/test"
  Normal   ExternalProvisioning   7m54s (x4 over 8m5s)  persistentvolume-controller                                                                               waiting for a volume to be created, either by external provisioner "named-disk.csi.cloud-director.vmware.com" or manually created by system administrator
  Normal   ProvisioningSucceeded  7m47s                 named-disk.csi.cloud-director.vmware.com_csi-vcd-controllerplugin-0_097b7dca-fddc-4972-bcc2-b0b6e9d30b62  Successfully provisioned volume pvc-acd8f9a9-dcd3-4735-9888-7d2d9748c659
  Warning  ExternalExpanding      7m11s                 volume_expand                                                                                             Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```

I can navigate to Datacenter -> Storage -> Named Disks in the vCD UI -> select the disk -> edit -> change the size and this is successful in vCenter. But the PVC is never updated.

### Reproduction steps

```bash
1. Create PVC
2. Edit PVC and change size - logs that plugin not capable
3. Edit PVC via vCD - not updated in k8s
```

### Expected behavior

It should be possible to expand the disk by editing the PVC. 
Alternatively if the PVC is expanded via vCD, this should be updated in the k8s PVC.
