### ISSUE TITLE
SecurityContext problem

### ISSUE THREAD

**Issue by erdembas** [vmware/cloud-director-named-disk-csi-driver#59]
### Describe the bug

I am using version 1.2.0 of this csi driver. When any disk is added, it creates the "mount" folder in this disk by giving "root" user privilege. When we use this disk in a pod running with a non-root user, a "Permission denied" error is received. How can I solve this problem?

![CleanShot 2022-06-06 at 17 55 03](https://user-images.githubusercontent.com/2093046/172186493-afb44d0b-a629-4f42-9e3b-032262779cc4.png)

This is pod ss. This pod securityContext user : 1000
![CleanShot 2022-06-06 at 17 55 40](https://user-images.githubusercontent.com/2093046/172186558-eba2b088-668a-4646-b14f-93550bec9cd2.png)

### Reproduction steps

```bash
I installed the contents with the manifests and got the attached errors.
```

### Expected behavior

""

**Comment by erdembas** [comment]
The example of the DigitalOcean worked is below.

![CleanShot 2022-06-06 at 17 58 27](https://user-images.githubusercontent.com/2093046/172187173-df5d4abd-a1e9-48cf-92ea-b085c1b7c02f.png)

**Comment by erdembas** [comment]
I am solved this problem. Added CSIDriver spec `fsGroupPolicy : File`

```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: named-disk.csi.cloud-director.vmware.com
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
```
